name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 
      
      - name: Build SAM Application
        run: sam build
      
      - name: Deploy CloudFormation stack
        run: 
         echo "y" | sam deploy --config-env default --capabilities CAPABILITY_IAM
