name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v1
        with:
          sam-cli-version: 'latest' # Ensure you have the latest version for SAM CLI
          sam-cli-telemetry: true

      - name: Build SAM Application
        run: sam build

      - name: Upload SAM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sam-artifacts
          path: .aws-sam/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: sam-artifacts
          path: .aws-sam/build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy CloudFormation stack
        run: echo "y" | sam deploy --config-env default --stack-name upstack --capabilities CAPABILITY_IAM
