name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <ap-south-1>  # e.g., us-east-1
      
      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://template.yml
      
      - name: Deploy CloudFormation stack
        run: aws cloudformation deploy --stack-name <upstashproject> --template.yml --capabilities CAPABILITY_IAM
